- name: webservers.yml
  hosts: webservers
  become: yes
  roles:
    - { role: common,    tags: ['common']}
    - { role: flask-app, tags: ['flask-app', 'flask']}
    - { role: nginx,     tags: ['nginx']}
